USER_PACKAGE_LOCATION = "user_package_location"
SYNC_PREFERENCES_FILE = "Sync Prerences.sublime-settings"
FILES_TO_EXCLUDE = "files_to_exclude_in_sync"
USER_ID = "user_id"
FOLDERS_TO_SYNC = "sync_folders"
